[package]
name = "sxfs"
description = "File server for auto uploads from the ShareX client with a web UI"
version = "0.1.0"
authors = ["DusterTheFirst <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.1"
handlebars = "1.1.0"
serde_json = "1.0.39"
lazy_static = "1.3.0"