name: Build
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
  lint-fmt:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint-fmt]
    strategy:
      matrix:
        target: [x86_64-apple-darwin, x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: prepare for upload
        run: cp target/release/sxfs target/release/sxfs-${{ matrix.target }}
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: sxfs-${{ matrix.target }}
          path: target/release